Table activity_logs {
  id int [pk, increment]
  user_id int [ref: > users.id]
  table_ref varchar
  action action
  message varchar
  device varchar
  origins varchar
  created_at timestamp
  updated_at timestamp
}