Table epics {
    id int [pk, increment]
    name varchar [not null]
    product_id int [ref: > products.id]
    created_at timestamp [default: `CURRENT_TIMESTAMP`]
    updated_at timestamp [default: `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`]
}