Table jobs {
  id int [pk, increment]
  title varchar
  instruction jsonb
  guide jsonb
  sop_id int [ref: > sops.id]
  spk_id int [ref: > spks.id]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}