Table positions {
    id int [pk, increment]
    name varchar [not null]
    department_id int [ref: > departments.id]
    created_at timestamp [default: `CURRENT_TIMESTAMP`]
    updated_at timestamp [default: `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`]
}