Table user_titles {
  id int [pk, increment]
  name varchar [not null]
  department_id int [ref: > departments.id]
  position_id int [ref: > positions.id]
  level_id int [ref: > levels.id]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`]
}