Table project_squads {
    id int [pk, increment]
    project_id int [ref: > projects.id]
    squad_id int [ref: > squads.id]
    created_at timestamp [default: `CURRENT_TIMESTAMP`]
    updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}