Table scrum_tasks {
  id int [pk, increment]
  nama varchar
  point int
  deskripsi text
  status_id int [ref: > statuses.id]
  prioritas prioritas
  pic int [ref: > users.id]
  dibuat_oleh int [ref: > users.id]
  project_id int [ref: > projects.id]
  tanggal_mulai date
  tanggal_selesai date
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`]
}