Table squads {
  id int [pk, increment]
  project_id int [ref: > projects.id]
  name varchar
  code varchar
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`]
}