// === TABLE: /entities/prd.dbml ===
Table prd {
    id INT [pk, increment]
}

// === TABLE: /entities/squad.dbml ===
Table squads {
    id int [pk, increment]
    name varchar
    team_id int [fk(team)]
}

// === TABLE: /entities/users.dbml ===
Table users {
  id int [pk, increment]
  name varchar
  email varchar
}


// === RELATION: /relation/squad_member/squad_member.dbml ===
Table squad_member {
    id int [pk, increment]  
    squad_id int [ref: > users.id] 
}