// === TABLE: /entities/menus.dbml ===
Table menus {
    id int [pk, increment]  
    label varchar
    path varchar
}

// === TABLE: /entities/roles.dbml ===
Table roles {
    id int [pk, increment]  
    name varchar
}

// === TABLE: /entities/users.dbml ===
Table users {
  id int [pk, increment]
  name varchar
  email varchar
}


// === RELATION: /relation/role_has_menus/role_has_menus.dbml ===
Table role_has_menus {
    id int [pk, increment]
    role_id int [ref: > roles.id]
    menu_id int [ref: > menus.id]
}

// === RELATION: /relation/user_has_roles/user_has_roles.dbml ===
Table user_has_roles {
    id int [pk, increment]  
    user_id int [ref: > users.id]
    role_id int [ref: > roles.id]
}