Table projects {
  id int [pk, increment]
  name varchar
  description text
  start_date date
  end_date date
  divisi_id int [ref: > divisi.id]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp
}